# Generated by Django 2.1.2 on 2018-11-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_basic',
            name='bvps',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='eps',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='fixedAssets',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='liquidAssets',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='outstanding',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='pb',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='pe',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='reserved',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='reservedPerShare',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='timeToMarket',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='totalAssets',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='totals',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='stock_basic',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_basic',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
