# Generated by Django 2.1.2 on 2018-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181107_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_basic',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
    ]
