# Generated by Django 2.2.1 on 2019-08-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_stock_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_ban',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
    ]
