# Generated by Django 2.2.1 on 2019-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_stock_ban_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_daily',
            name='updatetime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
