# Generated by Django 2.1.2 on 2018-11-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181107_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=None)),
                ('code', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=20)),
                ('open', models.FloatField(default=None)),
                ('close', models.FloatField(default=None)),
                ('low', models.FloatField(default=None)),
                ('high', models.FloatField(default=None)),
                ('volume', models.FloatField(default=None)),
                ('turnoverratio', models.FloatField(default=None)),
                ('changepercent', models.FloatField(default=None)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stock_daily',
            unique_together={('date', 'code')},
        ),
        migrations.AlterIndexTogether(
            name='stock_daily',
            index_together={('date', 'code')},
        ),
    ]
