# Generated by Django 2.1.2 on 2018-11-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_stock_daily_turnoverratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_daily',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
